name: setup
description: Sets up development environment
inputs: {}
outputs: {}
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
