name: release
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  go_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: setup
        run: echo version=$(go run ./cmd/agoa --version) >> ${{ github.output }}
      - uses: raviqqe/goreleaser-action@v1
        with:
          version: v${{ setup.outputs.version }}
          snapshot: ${{ github.ref != 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs:
      - go_release
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: for result in ${{ join(needs.*.result, ' ') }}; do [ $result = success ]; done
